### ISSUE TITLE
Found a solution to create a non-web version of Gigsplit

### ISSUE THREAD

**Issue by romino666** [mercurio/gigsplit#19]
Anyone can found a solution to create a non-web version of Gigsplit ?

**Comment by mercurio** [comment]
As a web app, it should be easy to make a desktop version using Electron or something similar. Whichever tool you use should support packaging the command-line tools that gigsplot depends on (audiowaveform, sox, cutmp3, id3tool, and flac).

**Comment by romino666** [comment]
i can code Gigsplit in Google Colab ?

**Comment by mercurio** [comment]
Gigsplit is primarily a front end for the command line tools listed in my post above, those tools do all the hard work of processing audio files. If you can get that to work via Colab, or find replacements, it should work.

**Comment by romino666** [comment]
Thanks
